CAFE/CAFE.Web/Controllers/AnnotationItemController.cs
using System;
using System.Web.Mvc;

namespace CAFE.Web.Controllers
{
    /// <summary>
    /// Anotation items view placeholder controller
    /// </summary>
    //[Authorize]
    public class AnnotationItemController : Controller
    {
        /// <summary>
        /// Returns main action
        /// </summary>
        /// <returns>Index view</returns>
        public ActionResult Index(Guid? id, Guid? cloningId, string filesId)
        {
            if (null == id && !User.Identity.IsAuthenticated)
                return RedirectToAction("Login", "Account");

            ViewBag.IsUserLoggedIn = User.Identity.IsAuthenticated;

            ViewBag.CloningId = cloningId;
            ViewBag.EditingId = id;
            ViewBag.FileIds = filesId;

            return View();
        }

        
        /// <summary>
        /// Returns main action
        /// </summary>
        /// <returns>Index view</returns>
        [HttpPost]
        public ActionResult CreateFromTemplate(Guid[] filesId, Guid? cloningId)
        {
            var filesIdsString = string.Join(",", filesId);
            if (null != cloningId)
            {
                ViewBag.CloningId = cloningId;
                return RedirectToAction("Index", new { cloningId = cloningId, filesId = filesIdsString });
            }

            return RedirectToAction("Index", new { filesId = filesIdsString });
        }

        /// <summary>
        /// Returns main action
        /// </summary>
        /// <returns>Index view</returns>
        [HttpGet]
        public ActionResult CreateFromTemplate(string filesIds, Guid? cloningId)
        {
            var filesIdsString = filesIds;
            if (null != cloningId)
            {
                ViewBag.CloningId = cloningId;
                return RedirectToAction("Index", new { cloningId = cloningId, filesId = filesIdsString });
            }

            return RedirectToAction("Index", new { filesId = filesIdsString });
        }

        [Authorize]
        public ActionResult Clone(Guid id)
        {
            return RedirectToAction("Index", new { cloningId = id });
        }
    }
}

CAFE/CAFE.Web/Controllers/SearchController.cs
using CAFE.Core.Configuration;
using CAFE.Core.Searching;
using CAFE.DAL.Interfaces;
using CAFE.DAL.Models;
using CAFE.Web.Models.Search;
using Microsoft.AspNet.Identity;
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace CAFE.Web.Controllers
{
    public class SearchController : Controller
    {
        private IRepository<DbAnnotationItem> _annotationItemsRepository;
        private IRepository<DbUserFile> _usersFilesRepository;
        private IConfigurationProvider _configurationProvider;
        private IRepository<DbUser> _usersRepository;
        private ISearchService _searchService;

        public SearchController(IRepository<DbAnnotationItem> annotationItemsRepository,
            IRepository<DbUserFile> usersFilesRepository, IConfigurationProvider configurationProvider,
            IRepository<DbUser> usersRepository, ISearchService searchService)
        {
            _annotationItemsRepository = annotationItemsRepository;
            _usersFilesRepository = usersFilesRepository;
            _configurationProvider = configurationProvider;
            _usersRepository = usersRepository;
            _searchService = searchService;
        }


        // GET: Search
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ResourceInfo(Guid id)
        {
            var model = new ResourceInfoModel();
            var userId = User.Identity.GetUserId();
            var currentUser = _usersRepository.Find(f => f.Id.ToString() == userId);

            if (_annotationItemsRepository.Select().Any(a => a.Id == id))
            {
                var foundAi = _annotationItemsRepository.Select().Where(w => w.Id == id).First();

                var firstDescription = foundAi.Object.References.Descriptions.First();
                model.Title = firstDescription.Title;
                model.Abstract = firstDescription.Abstract;
                model.OwnerName = foundAi.OwnerName;
                model.OwnerId = foundAi.OwnerId;

                if (null != userId)
                    model.HasAccess = _searchService.CheckThatAnnotationItemsIsAccessible(id, Guid.Parse(userId));

                model.Id = id;
                model.ResourceType = SearchResultItemType.AnnotationItem;
                model.Hosters = foundAi.Object.References.Hosters.Select(s => s.HosterName.Value).ToList();
                model.Link = "/AnnotationItem?id=" + id;

                foreach (var person in foundAi.Object.References.Persons)
                {
                    string email = "";
                    string phone = "";
                    string givenName = "";
                    string position = "";
                    string salutation = "";
                    string surname = "";

                    if (person.EmailAddress.Any())
                        email = person.EmailAddress.First();
                    if (person.PhoneNumber.Any())
                        phone = person.PhoneNumber.First();
                    if (person.GivenName.Any())
                        givenName = person.GivenName.First();
                    if (person.Position.Any())
                        position = person.Position.First().Value;
                    if (person.Salutation.Any())
                        salutation = person.Salutation.First();
                    if (person.SurName.Any())
                        surname = person.SurName.First();


                    model.Persons.Add(new PersonModel()
                    {
                        Email = email,
                        GivenName = givenName,
                        Phone = phone,
                        Position = position,
                        Salutation = salutation,
                        Surname = surname
                    });
                }
            }
            else if(_usersFilesRepository.Select().Any(a => a.Id == id))
            {
                var appConfig = _configurationProvider.Get<ApplicationConfiguration>();
                var basePath = appConfig.ApploadsRoot;
                var userFilesPath = Path.Combine(basePath, "UserFiles");

                var foundFile = _usersFilesRepository.Select().Where(w => w.Id == id).First();
                var fileExtension = Path.GetExtension(foundFile.Name);

                model.Title = foundFile.Name;
                model.Abstract = foundFile.Description;
                model.OwnerName = foundFile.Owner.Name;
                model.OwnerId = foundFile.Owner.Id.ToString();
                model.HasAccess = _searchService.CheckThatFileIsAccessible(id, Guid.Parse(userId));
                model.Id = id;
                model.ResourceType = SearchResultItemType.File;
                model.Link = userFilesPath + '/' + foundFile.Id + fileExtension;

            }
            else
            {
                throw new ApplicationException("Unknown file or annotation item");
            }
            return View(model);
        }

        
    }
}

CAFE/CAFE.Web/Views/Shared/AccountNotAccepted.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Account was not yet approved by administrator";
}

<div class="panel panel-warning">
    <div class="panel-heading"><h2>@ViewBag.Title</h2></div>
    <div class="panel-body">
        <p>Before first usage, your account must be approved by an administrator.</p>
        <p>Our administrator was already informed but of course it will take some time. Please be patient and try again in a while.</p>
    </div>

</div>

CAFE/CAFE.Web/Views/Shared/_Layout.cshtml
@using CAFE.Core.Misc
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - EASE</title>
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/admin/css")
    @RenderSection("styles", required: false)
    @Styles.Render("~/Content/css")
    <style type="text/css">
        body {
            background-color: #fafafa;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-fixed-top main-navbar">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><img src="/Content/images/logo.png" style="height: 100%;"></a>
            </div>
            <div class="navbar-collapse collapse" id="navbar-collapse" style="padding-right: 15px;">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
                        <li>@Html.ActionLink("New Annotation Item", "Index", "AnnotationItem")</li>
                    }
                    <li>@Html.ActionLink("Data search", "Index", "Search")</li>
                    @if (User.IsInRole(Constants.AdminRoleName))
                    {
                        <li>@Html.ActionLink("Administration", "Index", "Home", routeValues: new { area = "Admin" }, htmlAttributes: new object())</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    @*<div class="container body-content">*@
    @RenderBody()
    @*<hr />*@
    @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    @*</div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/global")
    @RenderSection("scripts", required: false)
</body>
</html>